### PR TITLE
UpdatedTemplate

### PR DESCRIPTION
**Pull request by gmentz**

### CODE REVIEW

**Review by gmentz — COMMENTED** [review]
bgfxx

**Comment by luost26** [comment]
It seems the merge direction is wrong. Have you tried "sync fork"?

**Comment by gmentz** [comment]
Apologies Shitong! Managed to sync the repo. Sorry for the inconvenience!

**Comment by luost26** [comment]
No worries! Thanks for using this template!!

**Comment by gmentz** [comment]
Thanks for providing it, and also for being so responsive!

If I can give a humble piece of feedback, if the text could be aligned in
the "short_bio" portion of the webpage and also wrap around the picture,
that would enhance the readability of the bio, which would be a great
addition to the website (IMO).

Thank you for making your template public, kind sir!

Best,
George

**Comment by gmentz** [comment]
Those screenshots looks aesthetically pleasing for both the wide and narrow
screen. I believe the only thing that could also help the reader would be
to have justified alignment in the text (so that margins are equal on the
left and right side).

Thanks again for your response and for your awesome template!

**Comment by luost26** [comment]
True! I have added an option for justified text alignment.

**Comment by luost26** [comment]
All these updates have been pushed to the main branch!

**Comment by gmentz** [comment]
Thank you sm!

**Comment by gmentz** [comment]
Hi Shitong,

Does your template currently offer options to add projects, similar to
Al-folio: https://alshedivat.github.io/al-folio/projects/.

Thanks,
George

**Comment by luost26** [comment]
Probably not. But I think the Showcase functionality can meet this need —
you can make a page similar to Al-folio project page with it

**Comment by gmentz** [comment]
Thanks, I will give it a try. Would it be possible to have 2-3 showcase
pages associated with a profile? Also, thanks for the extremely prompt
response!

**Comment by luost26** [comment]
Yes it is possible. Just make copies of the showcase.html page, and add
different filtering conditions for each of them, that's all.

**Comment by gmentz** [comment]
Awesome, thank you so much!

**Comment by gmentz** [comment]
Hey Shitong, I made an academic project page based on your template. Here
is an example: https://gmentz.github.io/seegnificant. I would be happy to
share the code for this for you to include in the academic homepage, if
you'd like.

**Comment by luost26** [comment]
Yeah, that is great! Thanks

Actually I am considering implementing article pages, similar to al-folio's blogpost feature ([https://alshedivat.github.io/al-folio/blog/2021/distill/](https://alshedivat.github.io/al-folio/blog/2021/distill/)). I think your implementation would be a great starting point!

**Comment by luost26** [comment]
Last time you asked about al-folio project page feature. I thought you were referring to their card-based display (https://alshedivat.github.io/al-folio/projects ). Sorry for the misunderstanding. Actually the Showcase function is meant to display cards rather than project details.

But yes, we definitely also need project page feature like https://alshedivat.github.io/al-folio/projects/1_project/ . To me, it is the same as blogpost feature. Your implementation looks great and I hope I can start working on it soon.

**Pull request closed without merging**
